# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Placeholder'),
        ),
    ]
